<a href="https://colab.research.google.com/github/aditikapoor2441/IPL-Data-Analysis/blob/main/IPL_Data_Analytics_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
#Load matches dataset
matches=pd.read_csv('matches.csv')
#Show first 5 rows
matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [2]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

In [3]:
matches.describe()

                 id  result_margin  target_runs  target_overs
count  1.095000e+03    1076.000000  1092.000000   1092.000000
mean   9.048283e+05      17.259294   165.684066     19.759341
std    3.677402e+05      21.787444    33.427048      1.581108
min    3.359820e+05       1.000000    43.000000      5.000000
25%    5.483315e+05       6.000000   146.000000     20.000000
50%    9.809610e+05       8.000000   166.000000     20.000000
75%    1.254062e+06      20.000000   187.000000     20.000000
max    1.426312e+06     146.000000   288.000000     20.000000

In [4]:
matches.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

In [5]:
matches['winner'].value_counts()

winner
Mumbai Indians                 144
Chennai Super Kings            138
Kolkata Knight Riders          131
Royal Challengers Bangalore    116
Rajasthan Royals               112
Sunrisers Hyderabad             88
Kings XI Punjab                 88
Delhi Daredevils                67
Delhi Capitals                  48
Deccan Chargers                 29
Gujarat Titans                  28
Punjab Kings                    24
Lucknow Super Giants            24
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Royal Challengers Bengaluru      7
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: count, dtype: int64

In [8]:
team_wins=matches['winner'].value_counts().reset_index()
team_wins.columns=['team','wins']
team_wins

                           team  wins
0                Mumbai Indians   144
1           Chennai Super Kings   138
2         Kolkata Knight Riders   131
3   Royal Challengers Bangalore   116
4              Rajasthan Royals   112
5           Sunrisers Hyderabad    88
6               Kings XI Punjab    88
7              Delhi Daredevils    67
8                Delhi Capitals    48
9               Deccan Chargers    29
10               Gujarat Titans    28
11                 Punjab Kings    24
12         Lucknow Super Giants    24
13                Gujarat Lions    13
14                Pune Warriors    12
15       Rising Pune Supergiant    10
16  Royal Challengers Bengaluru     7
17         Kochi Tuskers Kerala     6
18      Rising Pune Supergiants     5

In [9]:
team_wins=team_wins.sort_values(by='wins',ascending=False)
team_wins

                           team  wins
0                Mumbai Indians   144
1           Chennai Super Kings   138
2         Kolkata Knight Riders   131
3   Royal Challengers Bangalore   116
4              Rajasthan Royals   112
5           Sunrisers Hyderabad    88
6               Kings XI Punjab    88
7              Delhi Daredevils    67
8                Delhi Capitals    48
9               Deccan Chargers    29
10               Gujarat Titans    28
11                 Punjab Kings    24
12         Lucknow Super Giants    24
13                Gujarat Lions    13
14                Pune Warriors    12
15       Rising Pune Supergiant    10
16  Royal Challengers Bengaluru     7
17         Kochi Tuskers Kerala     6
18      Rising Pune Supergiants     5

In [10]:
team_wins.to_csv('team_wins.csv',index=False)

In [11]:
matches['toss_match_winner']=matches['toss_winner']==matches['winner']

In [12]:
matches['toss_match_winner'].value_counts()

toss_match_winner
True     554
False    541
Name: count, dtype: int64

In [14]:
matches['toss_match_winner'].value_counts(normalize=True)*100

toss_match_winner
True     50.593607
False    49.406393
Name: proportion, dtype: float64

In [15]:
toss_analysis=matches['toss_match_winner'].value_counts().reset_index()
toss_analysis. columns = ['toss_result','count']
toss_analysis.to_csv('toss_analysis.csv',index=False)